# Generated by Django 5.0.14 on 2026-07-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_completed',
            new_name='is_profile_completed',
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_completion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter'), ('CANDIDATE', 'Candidate')], db_index=True, default='CANDIDATE', max_length=20),
        ),
    ]
