# Generated by Django 5.0.14 on 2026-07-02 14:16

import apps.common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to=apps.common.utils.get_file_upload_path)),
                ('company_cover', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.get_file_upload_path)),
                ('company_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('company_culture', models.TextField(blank=True, null=True)),
                ('company_benefits', models.JSONField(blank=True, default=list)),
                ('industry', models.CharField(max_length=150)),
                ('website', models.URLField()),
                ('linkedin', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('founded_year', models.PositiveIntegerField()),
                ('company_size', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('recruiter', models.OneToOneField(limit_choices_to={'role': 'RECRUITER'}, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
